[package]
name = "ticker-sniffer-build-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
bincode = "1.3.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.110"
