[package]
name = "ticker-sniffer-build-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.110"
ticker-sniffer-common-lib = { path = "../ticker-sniffer-common-lib" }
