// Automatically generated file. Do not edit.
// Generated by embed-bytes crate.

pub static COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY: &[u8] = include_bytes!("embed/COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY.bin");
