// Automatically generated file. Do not edit.
// Generated by embed-bytes crate.

pub struct ResourceContainer;

impl ResourceContainer {

    pub const COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY: &'static [u8] = include_bytes!("../../embedded_storage/COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY.bin");
}
