use crate::models::DocumentCompanyNameExtractorConfig;

pub const DEFAULT_COMPANY_NAME_EXTRACTOR_CONFIG: DocumentCompanyNameExtractorConfig =
    DocumentCompanyNameExtractorConfig {
        min_text_doc_token_sim_threshold: 0.99,
        continuity_reward: 1.5,
        confidence_score_duplicate_threshold: 2,
        low_confidence_penalty_factor: 0.5,
        min_confidence_level_threshold: 0.5,
    };

pub const DEFAULT_RESULT_BIAS_ADJUSTER_WEIGHTS: &[(u64, f32)] = &[];

pub const DEFAULT_BIAS_ADJUSTER_SCORE: f32 = 0.5;

// TODO: Replace w/ https://crates.io/crates/url?
// (may be completely overkill for this use case; just need TLDs)
pub const TLD_LIST: [&str; 5] = ["com", "org", "net", "edu", "gov"];

// TODO: Ideally, instead of hardcoding this list, it would be nice to include
// a utility to learn the words to use and how to properly weigh them. The
// list could be learned from expected/actual results from the test cases,
// and be wrapped up in the same tuning process that was used before.
//
// Alternatively, what might be actually a lot easier, is to look at the most
// common first n-positioned words in the corpus, and have the
// `DocumentTokenProcessor` do its own automatic filtering, or substitution.
pub const IGNORE_WORDS: &[&str] = &[
    // Many State Street ETFs are commonly referenced without SPDR prefix
    // "SPDR", "U.S.", "Strong",
];

pub const STOP_WORDS: &[&str] = &[
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "aren't",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can",
    "can't",
    "cannot",
    "could",
    "couldn't",
    "did",
    "didn't",
    "do",
    "does",
    "doesn't",
    "doing",
    "don't",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "hadn't",
    "has",
    "hasn't",
    "have",
    "haven't",
    "having",
    "he",
    "he'd",
    "he'll",
    "he's",
    "her",
    "here",
    "here's",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "how's",
    "i",
    "i'd",
    "i'll",
    "i'm",
    "i've",
    "if",
    "in",
    "into",
    "is",
    "isn't",
    "it",
    "it's",
    "its",
    "itself",
    "let's",
    "me",
    "more",
    "most",
    "mustn't",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "shan't",
    "she",
    "she'd",
    "she'll",
    "she's",
    "should",
    "shouldn't",
    "so",
    "some",
    "such",
    "than",
    "that",
    "that's",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "there's",
    "these",
    "they",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "wasn't",
    "we",
    "we'd",
    "we'll",
    "we're",
    "we've",
    "were",
    "weren't",
    "what",
    "what's",
    "when",
    "when's",
    "where",
    "where's",
    "which",
    "while",
    "who",
    "who's",
    "whom",
    "why",
    "why's",
    "with",
    "won't",
    "would",
    "wouldn't",
    "you",
    "you'd",
    "you'll",
    "you're",
    "you've",
    "your",
    "yours",
    "yourself",
    "yourselves",
];
