// Automatically generated file. Do not edit.
// Generated by build-resource-byte-arrays crate.

#[cfg(feature = "build_resource_byte_arrays")]
pub static COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY: &[u8] = include_bytes!(concat!(env!("OUT_DIR"),"/bin/COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY.bin"));

#[cfg(not(feature = "build_resource_byte_arrays"))]
pub static COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY: &[u8] = &[];

#[cfg(not(feature = "build_resource_byte_arrays"))]
#[ctor::ctor]
fn warn_COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY_empty() {
    eprintln!("Warning: `COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY` is empty because the `build_resource_byte_arrays ` feature is not enabled.");
}

