// Automatically generated file. Do not edit.
// Generated by build-resource-byte-arrays crate.

#[cfg(feature = "build_resource_byte_arrays")]
include!("dynamic_resources_generated.rs");
#[cfg(not(feature = "build_resource_byte_arrays"))]
mod dynamic_resources_fallback {
    pub static COMPRESSED_COMPANY_SYMBOL_LIST_BYTE_ARRAY: &[u8] = &[];
}
#[cfg(not(feature = "build_resource_byte_arrays"))]
pub use dynamic_resources_fallback::*;
